### ISSUE TITLE
etcd_v3api.lua 的 set 方法无法处理值为 string 类型的情形

### ISSUE THREAD

**Issue by antsmallant** [HahahaVal/easy_game#1]
## 问题描述
```    
local opts = {
    hosts = {"127.0.0.1:2379"},
    user = "root",
    password = "123456",
} 
local etcd_cli = Etcd.new(opts)
etcd_cli:set("/node1", "127.0.0.1:8001")
local getret = etcd_cli:get("/node1")
skynet.error("node1:", getret.kvs and getret.kvs and getret.kvs[1] and getret.kvs[1].value)
```

以上代码预期得到的输出是 node1: 127.0.0.1:8001，但实际上输出是 node1: 127.0

## 问题分析
看了一下 [https://github.com/HahahaVal/easy_game/blob/main/lualib/etcd_v3api.lua](https://github.com/HahahaVal/easy_game/blob/main/lualib/etcd_v3api.lua) 的实现，在 `function mt:_set(key, value, attr)` 里面调用了 `serialize_and_encode_base64`，而 `serialize_and_encode_base64` 判断 value 为 table 的情况下才调用 `encode_json`，`serialize_and_encode_base64`  代码是这样的
```
local function serialize_and_encode_base64(value)
    if tab_exist(value) then
        value = encode_json(value)
    end

    if not value then
        return false
    end
    return encode_base64(value)
end
```
然而，在 `function mt:_get(key, attr)` 处理 kvs 的时候，是这样的：
```
    if rspData.kvs and next(rspData.kvs) then
        for _, kv in ipairs(rspData.kvs) do
            kv.key = decode_base64(kv.key)
            kv.value = decode_base64(kv.value or "")
            kv.value = decode_json(kv.value)
        end
    end
```
无论 value 为何值，都调用了 `decode_json`，这与前面 `function mt:_set(key, value, attr)` 里的实现不完全匹配了，`_set` 只在 value 为 table 的情况下才 `encode_json`。

## 问题解决
为了解决这个问题，可以把 `serialize_and_encode_base64` 里的 table 判断去掉，改成这样：
```
local function serialize_and_encode_base64(value)
    value = encode_json(value)
    if not value then
        return false
    end
    return encode_base64(value)
end
```

## 其他的
实际上，我看到 [https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua](https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua) 的 `serialize_and_encode_base64` 实现并没有判断 data 是否为 table ，它的代码如下：
```
local function serialize_and_encode_base64(serialize_fn, data)
    local err
    data, err = serialize_fn(data)
    if not data then
        return nil, err
    end
    return encode_base64(data)
end
```

**Comment by HahahaVal** [comment]
是有这个问题，已经修复，感谢指出
